global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: 'node-sys'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: node
    file_sd_configs:
      - files:
        - nodes/*.yml
    metric_relabel_configs:
      - regex: "^(job|instance)$"
        action: labeldrop

